# /*******************************************************************************
#  * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
#  * in compliance with the License. You may obtain a copy of the License at
#  *
#  * http://www.apache.org/licenses/LICENSE-2.0
#  *
#  * Unless required by applicable law or agreed to in writing, software distributed under the License
#  * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
#  * or implied. See the License for the specific language governing permissions and limitations under
#  * the License.
#  *
#  * @author
#  * Andre Srinivasan
#  * added: April, 2020
#  *******************************************************************************/

version: '3.4'

volumes:
  db-secrets:
  db-data:

services:
  secret-creator:
    image: alpine:latest
    container_name: secret-creator
    command: |
      /bin/sh -cx "
      echo 'foobarbaz' >/secrets/redispass.txt
      while true; do sleep 1000; done
      "
    volumes:
      - db-secrets:/secrets:z

  redis:
    image: redis:5.0.8-alpine
    container_name: secured-redis
    ports:
      - "6379:6379"
    hostname: redis
    command: |
      /bin/sh -cx "
      /usr/local/bin/docker-entrypoint.sh --requirepass `cat /secrets/redispass.txt` --dir /data
      "
    volumes:
      - db-data:/data:z
      - db-secrets:/secrets:z
    depends_on:
      - secret-creator

##     command: ["sh", "-cx", "echo 'foobarbaz' >/secrets/redispass.txt; while true; do sleep 1000; done"]
## ["--requirepass password"]
      